### ISSUE TITLE
Constant stack usage

### ISSUE THREAD

**Issue by gabejohnson** [gilbert/es-pipeline-operator#47]
The current proposal desugars
```js
"hello"
  |> doubleSay
  |> capitalize
  |> exclaim;
```
to
```js
exclaim(capitalize(doubleSay("hello")));
```
If I want to reuse this pipeline I can write
```js
const sayItAgainLouder = s => s |> doubleSay |> capitalize |> exclaim;
```
Now I get reuse, but I'm allocating three stack frames. This isn't a big deal unless I want to compose `sayItAgainLouder` with some other functions.

A simple alternative desugaring
```js
[doubleSay, capitalize, exclaim].reduce((value, f) => f(value), "hello");
```
This decreases stack usage, but I imagine at the cost of speed.

It would be useful if this proposal required the compiler to maintain constant stack usage through either some sort of stream fusion or stack frame reuse.

**Comment by jasmith79** [comment]
I don't think that's within the intended uses: if you want to compose pipelines you'll be using `compose` rather than an infix operator. Ditto for long chains using the stack: if your pipeline is ridiculously long then it should probably be built up using `compose` in pieces rather than one long chain that fills more than your text editor can display.

**Comment by gabejohnson** [comment]
> if you want to compose pipelines you'll be using compose rather than an infix operator.

I might agree with you @jasmith79 _if_ there was a builtin `compose` that guaranteed constant stack usage.

I'm all for a built-in though. See https://github.com/fantasyland/ECMAScript-proposals/issues/1

> Ditto for long chains using lots of stack space: if your pipeline is ridiculously long then it should probably be built up using compose in pieces rather than one long chain that fills more than your text editor can display.

I haven't suggested this usage. I _did_ mention composing functions with _other_ composed functions.

**Comment by dtinth** [comment]
If I understand correctly,

```js
exclaim(capitalize(doubleSay("hello")))
```

works like

```js
let _tmp = "hello"
_tmp = doubleSay(_tmp)
_tmp = capitalize(_tmp)
_tmp = exclaim(_tmp)
_tmp
```

Therefore there is no nested stack frame?

**Comment by gabejohnson** [comment]
@dtinth you're right. For some reason I was thinking the behavior was the same as how some `pipe` functions are implemented resulting in something like
```js
(x => exclaim((x => capitalize((x => doubleSay(x))(x)))(x)))('hello')
```
which it does not.
